#!/bin/bash
# ced
# Script to setup a linux server with some basic apps and configs

###
# Vars
###
export cwd=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd ) || /opt/ced
export public_ip=$(curl -s http://whatismyip.akamai.com/)
export third_party=$cwd/thirdparty
export config_path=$cwd/config.conf
export cli_use_name="ced"
export logloc=$cwd/logs/ced.log # Custom logs produced in this file
export aptlogloc=$cwd/logs/apt.log  # Logs produced by apt 
export cmdlogloc=$cwd/logs/cmd.log  # Logs produced by applications run in here
export property=""
export os=$(cat /etc/os-release)
export curuser=$(who am i | awk '{print $1}')
# export logname=$(logname 2> $logloc)
export sudouser="${SUDO_USER:-$USER}"
export adminusr="${sudouser:-$curuser}"

###
# Colors
###
RED="\\e[31m"
GREEN="\\e[32m"
CYAN="\\e[0;36m"
YELLOW="\\e[0;33m"
ENDCOLOR="\\e[0m"

# Load common functions and commands
load_func() {
  for filename in $1; do
    source "$filename"
  done
}
load_func "$cwd/common/*.sh"
load_func "$cwd/commands/*"

# Create config file if not present
if [ $(file_exists $config_path) = false ]; then
  cp $cwd/config.template $config_path
fi

case $1 in
  "")
    update
    if [ $(get_conf "first_run") = true ]; then
      log "First time run" DEBUG
      command_setup ""
      set_conf "first_run" false
    fi
    exit 0
    ;;
  i|install)
    shift
    update
    command_install $@
    ;;
  s|setup)
    shift
    update
    command_setup $2
    ;;
  help)
    cli_help
    ;;
  -*|--*)
    log "Unknown option $1. Use ced help to show a list of options" WARN
    ;;
  *)
    cli_help
    ;;
esac