#!/bin/bash
# ced
# Script to setup a linux server with some basic apps and configs

###
# Vars
###
export cwd=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd ) || /opt/ced
export third_party=$cwd/thirdparty
export config_path=$cwd/config.conf
export cli_use_name="ced"
export logloc=$cwd/logs/install.log # Custom logs produced in this file
export aptlogloc=$cwd/logs/apt.log  # Logs produced by apt 
export cmdlogloc=$cwd/logs/cmd.log  # Logs produced by applications run in here
export property=''
export os=$(cat /etc/os-release)
export curuser=$(who am i | awk '{print $1}')
# export logname=$(logname 2> $logloc)
export sudouser="${SUDO_USER:-$USER}"
export adminusr="${sudouser:-$curuser}"

###
# Colors
###
RED="\\e[31m"
GREEN="\\e[32m"
CYAN="\\e[0;36m"
YELLOW="\\e[0;33m"
ENDCOLOR="\\e[0m"

# Create config file if not present
touch $config_path

# Load common functions and commands
load_func() {
  for filename in $1; do
    . $filename
  done
}
load_func($cwd/common/*.sh)
load_func($cwd/common/*)

# Validate arguments
case "$1" in
  "")
  update
  if [[ $(prop "first_run" $config_path) = true ]]; then
    log "First time run" DEBUG
    command_init "all"
    setconf "first_run" false
  fi
  ;;
  init)
  update
  command_init $2
  ;;
  i|install)
  update
  command_install $2
  ;;
  *)
  cli_help
  ;;
esac
