#!/bin/bash

command_install_help() {
  print_help "install" "
    docker:
    webmin:
    nginx:
    portainer:
    vsftpd:
    certbot:
  "
  exit 1
}

command_install() {
  case "$1" in
    "all")
    install_ufw
    install_ssh
    install_fail2ban
    install_docker
    install_webmin
    install_nginx
    install_portainer
    install_vsftpd
    install_certbot
    ;;
    "ufw")
    install_ufw
    ;;
    "fail2ban")
    install_fail2ban
    ;;
    "ssh")
    install_ssh
    ;;
    "docker")
    install_docker   
    ;;
    "webmin")
    install_webmin
    ;;
    "nginx")
    install_nginx
    ;;
    "selinux")
    install_selinux
    ;;
    "portainer")
    install_portainer
    ;;
    "vsftpd")
    install_vsftpd
    ;;
    "certbot")
    install_certbot
    ;;
    *)
    command_install_help
    ;;
  esac

  log "Installation complete." INFO
}
